name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: "${{ github.token }}"

      - name: Deploy project to Glitch
        run: |
          npx glitcheroo deploy
        env:
          GLITCH_SECRET_URL: ${{ secrets.GLITCH_SECRET_URL }}

      - name: Set ENVIRONMENT_URL environment variable
        run: |
          echo "ENVIRONMENT_URL=https://glitch.com/~$(basename "${GLITCH_SECRET_URL}")" >> $GITHUB_ENV
        env:
          GLITCH_SECRET_URL: ${{ secrets.GLITCH_SECRET_URL }}
        
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          environment_url: "${{ env.ENVIRONMENT_URL }}"
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          environment_url: "${{ env.ENVIRONMENT_URL }}"
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}